version: '2'
services:
 nginx:
  build:
   context: .
  environment:
      - VIRTUAL_HOST=${domain}
  volumes:
    - ./static:/usr/share/nginx/html
    - ./logs:/usr/share/nginx/logs
  ports:
    - "80:80"
    - "443:443"
